# Generated by Django 3.2.8 on 2021-10-11 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_details', models.JSONField(blank=True, default=dict, null=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('email_id', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('user_mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('dialing_code', models.CharField(blank=True, max_length=8, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='male', max_length=16)),
                ('user_dob', models.DateField(blank=True, null=True)),
                ('country_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.countrydatamodel')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
