# Generated by Django 3.2.8 on 2021-10-11 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_countrydatamodel_icon_link'),
        ('users', '0002_usersmodel_profile_pic_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='country_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.countrydatamodel'),
        ),
    ]
