# Generated by Django 3.2.8 on 2021-10-11 22:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_details', models.JSONField(blank=True, default=dict, null=True)),
                ('country_name', models.CharField(max_length=64)),
                ('iso_code', models.CharField(max_length=16)),
                ('dialing_code', models.IntegerField()),
                ('time_zone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('UTC[+-][0-9]{2}:[0-9]{2}')])),
                ('icon_link', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'country_data',
            },
        ),
    ]
