# Generated by Django 3.2.8 on 2021-10-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydatamodel',
            name='icon_link',
            field=models.CharField(max_length=256),
        ),
    ]
