# Generated by Django 3.2.8 on 2021-10-11 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_details', models.JSONField(blank=True, default=dict, null=True)),
                ('platform', models.CharField(default='google', max_length=256)),
                ('platform_token', models.TextField(blank=True, editable=False)),
                ('client_id', models.CharField(max_length=64, unique=True)),
                ('client_type', models.CharField(max_length=16)),
                ('client_description', models.TextField(blank=True, editable=False, null=True)),
                ('ipv4_address', models.CharField(max_length=16)),
                ('session_token', models.CharField(blank=True, db_index=True, editable=False, max_length=256, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usersmodel')),
            ],
            options={
                'db_table': 'user_login',
            },
        ),
        migrations.CreateModel(
            name='UserPlatformProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_details', models.JSONField(blank=True, default=dict, null=True)),
                ('email_id', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(default='', max_length=256)),
                ('profile_pic_link', models.URLField(max_length=500)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='male', max_length=16)),
                ('platform', models.CharField(default='google', max_length=64)),
                ('platform_user_id', models.CharField(max_length=256)),
                ('data', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usersmodel')),
            ],
            options={
                'db_table': 'user_platform_profile',
                'unique_together': {('email_id', 'platform')},
            },
        ),
    ]
